### ISSUE TITLE
Unthemed Chat Input Box

### ISSUE THREAD

**Issue by masroof-maindak** [Saltssaumure/neobrutal-discord-theme#5]
Loving the theme, there's just one small thing that I noticed is different from the screenshots, the main text box isn't themed.

![image](https://github.com/user-attachments/assets/122813ac-9d61-412f-9729-50e0c392fb23)

This is my quickCss at the moment:

```css
.theme-light {
    --neobrutal-color-1: #DDCEBC;
    --neobrutal-color-2: #f1e3d1;
    --neobrutal-color-text: #64513e;
    --neobrutal-color-accent: #bf7979;
}
```

Not a huge problem and I don't mind it personally but I thought I'd let you know.
